delete from genre;
-- Example data
insert into genre (name) values
         ('Action')
        ,('Adventure')
        ,('Animation')
        ,('Biography')
        ,('Comedy')
        ,('Crime')
        ,('Documentary')
        ,('Drama')
        ,('Family')
        ,('Fantasy')
        ,('Film-Noir')
        ,('Game-Show')
        ,('History')
        ,('Horror')
        ,('Music')
        ,('Musical')
        ,('Mystery')
        ,('News')
        ,('Reality-TV')
        ,('Romance')
        ,('Sci-Fi')
        ,('Sport')
        ,('Talk-Show')
        ,('Thriller')
        ,('War')
        ,('Western');